<div class="space-y-8" x-data="{ openFilter: @entangle('openFilter') }"><div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 px-1"><div><x-h1>{{ __('Sales') }}</x-h1><x-short-description>{{ __('List of ' . strtolower('Sales')) }}</x-short-description></div><div class="flex items-center gap-3">@if($search || $openFilter)<button wire:click="resetFilters" class="inline-flex items-center gap-1.5 px-3 py-2 text-xs font-bold text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-2xl transition-none"><span>{{ __('Reset') }}</span></button>@endif <button @click="openFilter = !openFilter" class="inline-flex items-center gap-2 px-4 py-2.5 text-sm font-semibold text-gray-600 dark:text-gray-400 bg-white dark:bg-gray-800 border border-gray-100 dark:border-gray-700 rounded-2xl shadow-sm transition-none"><span>{{ __('Filters') }}</span></button> @can('add_sales')<x-btn :href="route('admin.sales.create')" icon="plus">{{ __('Add Sale') }}</x-btn>@endcan</div></div><div x-show="openFilter" x-cloak x-transition:enter="transition ease-out duration-300" x-transition:enter-start="opacity-0 -translate-y-4" class="p-6 bg-white dark:bg-gray-800 border border-gray-100 dark:border-gray-700 rounded-[2rem] shadow-sm"><div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6"><div><label class="block mb-1.5 text-[10px] font-bold text-gray-900 dark:text-gray-100 uppercase tracking-widest ml-1">{{ __('Search') }}</label><input wire:model.live.debounce.300ms="search" type="text" placeholder="{{ __('Search') }}..." class="w-full p-3 text-sm font-bold bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-2xl focus:ring-2 focus:ring-blue-500/20 transition shadow-sm dark:text-white"></div>            <div><x-form.dropdown-search wire:model.live="user_id" :label="__('User Id')" :data="$users" :placeholder="__('Filter User Id')" /></div>
            <div><x-form.dropdown-search wire:model.live="product_id" :label="__('Product Id')" :data="$products" :placeholder="__('Filter Product Id')" /></div>
</div></div>@include('errors.messages')<div class="overflow-hidden bg-white dark:bg-gray-800 rounded-[2rem] border border-gray-50 dark:border-gray-700 shadow-sm"><div class="overflow-x-auto"><table class="w-full text-sm text-left text-gray-500 dark:text-gray-400"><thead class="bg-gray-50/50 dark:bg-gray-900/50"><tr>                <x-table.th name="id" :label="__('ID')" :$sortField :$sortAsc :sortable="in_array('id', $sortableFields)" />
                <x-table.th name="user_id" :label="__('User Id')" :$sortField :$sortAsc :sortable="in_array('user_id', $sortableFields)" />
                <x-table.th name="product_id" :label="__('Product Id')" :$sortField :$sortAsc :sortable="in_array('product_id', $sortableFields)" />
                <x-table.th name="quantity" :label="__('Quantity')" :$sortField :$sortAsc :sortable="in_array('quantity', $sortableFields)" />
                <x-table.th name="total_price" :label="__('Total Price')" :$sortField :$sortAsc :sortable="in_array('total_price', $sortableFields)" />
                <x-table.th name="sale_date" :label="__('Sale Date')" :$sortField :$sortAsc :sortable="in_array('sale_date', $sortableFields)" />
                <x-table.th name="status" :label="__('Status')" :$sortField :$sortAsc :sortable="in_array('status', $sortableFields)" />
                <x-table.th name="notes" :label="__('Notes')" :$sortField :$sortAsc :sortable="in_array('notes', $sortableFields)" />
                <x-table.th name="no" :label="__('No')" :$sortField :$sortAsc :sortable="in_array('no', $sortableFields)" />
<th class="px-4 py-4 text-right text-[10px] font-black uppercase text-gray-400 tracking-widest">{{ __('Action') }}</th></tr></thead><tbody class="divide-y divide-gray-50 dark:divide-gray-700/50">@foreach($items as $item)<livewire:admin.sales.row :$item :key="$item->id" />@endforeach</tbody></table></div><div class="p-4 border-t border-gray-50 dark:border-gray-700/50">{{ $items->links() }}</div></div></div>